/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* f:(i0[6],i1[2])->(o0[6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #7: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #8: @1 = 0.6 */
  w1 = 5.9999999999999998e-01;
  /* #9: @1 = (@1*@0) */
  w1 *= w0;
  /* #10: @0 = 3.14159 */
  w0 = 3.1415926535897931e+00;
  /* #11: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #12: @0 = (@0+@2) */
  w0 += w2;
  /* #13: @2 = 2 */
  w2 = 2.;
  /* #14: @0 = (@0/@2) */
  w0 /= w2;
  /* #15: @0 = tan(@0) */
  w0 = tan( w0 );
  /* #16: @1 = (@1/@0) */
  w1 /= w0;
  /* #17: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #18: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #19: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #20: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #21: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #22: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #23: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  return 0;
}

/* avant_dyn_disc_phi_fun:(i0[6],i1[2],i2[5])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+9, w7, w8, *w9=w+17, *w10=w+23, *w11=w+29, *w12=w+31;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @0 = input[2][3] */
  w0 = arg[2] ? arg[2][3] : 0;
  /* #8: @1 = 6 */
  w1 = 6.;
  /* #9: @1 = (@0/@1) */
  w1  = (w0/w1);
  /* #10: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #11: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #12: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #13: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #14: @8 = 0.6 */
  w8 = 5.9999999999999998e-01;
  /* #15: @8 = (@8*@5) */
  w8 *= w5;
  /* #16: @5 = 3.14159 */
  w5 = 3.1415926535897931e+00;
  /* #17: @5 = (@5+@3) */
  w5 += w3;
  /* #18: @3 = 2 */
  w3 = 2.;
  /* #19: @5 = (@5/@3) */
  w5 /= w3;
  /* #20: @5 = tan(@5) */
  w5 = tan( w5 );
  /* #21: @8 = (@8/@5) */
  w8 /= w5;
  /* #22: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #23: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #24: @9 = vertcat(@7, @2, @8, @4, @5, @3) */
  rr=w9;
  *rr++ = w7;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w3;
  /* #25: @7 = 2 */
  w7 = 2.;
  /* #26: @7 = (@0/@7) */
  w7  = (w0/w7);
  /* #27: @10 = (@7*@9) */
  for (i=0, rr=w10, cs=w9; i<6; ++i) (*rr++)  = (w7*(*cs++));
  /* #28: @10 = (@6+@10) */
  for (i=0, rr=w10, cr=w6, cs=w10; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #29: @11 = vertcat(@5, @3) */
  rr=w11;
  *rr++ = w5;
  *rr++ = w3;
  /* #30: @12 = f(@10, @11) */
  arg1[0]=w10;
  arg1[1]=w11;
  res1[0]=w12;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #31: @10 = (2.*@12) */
  for (i=0, rr=w10, cs=w12; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #32: @9 = (@9+@10) */
  for (i=0, rr=w9, cs=w10; i<6; ++i) (*rr++) += (*cs++);
  /* #33: @5 = 2 */
  w5 = 2.;
  /* #34: @5 = (@0/@5) */
  w5  = (w0/w5);
  /* #35: @12 = (@5*@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) (*rr++)  = (w5*(*cs++));
  /* #36: @12 = (@6+@12) */
  for (i=0, rr=w12, cr=w6, cs=w12; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #37: @10 = f(@12, @11) */
  arg1[0]=w12;
  arg1[1]=w11;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #38: @12 = (2.*@10) */
  for (i=0, rr=w12, cs=w10; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #39: @9 = (@9+@12) */
  for (i=0, rr=w9, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #40: @10 = (@0*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #41: @10 = (@6+@10) */
  for (i=0, rr=w10, cr=w6, cs=w10; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #42: @12 = f(@10, @11) */
  arg1[0]=w10;
  arg1[1]=w11;
  res1[0]=w12;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #43: @9 = (@9+@12) */
  for (i=0, rr=w9, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #44: @9 = (@1*@9) */
  for (i=0, rr=w9, cs=w9; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #45: @6 = (@6+@9) */
  for (i=0, rr=w6, cs=w9; i<6; ++i) (*rr++) += (*cs++);
  /* #46: output[0][0] = @6 */
  casadi_copy(w6, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int avant_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real avant_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 37;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
