/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[5] = {6, 1, 0, 1, 4};
static const casadi_int casadi_s1[5] = {6, 1, 0, 1, 2};
static const casadi_int casadi_s2[7] = {6, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[6] = {6, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[5] = {6, 1, 0, 1, 3};
static const casadi_int casadi_s5[6] = {6, 1, 0, 2, 2, 3};
static const casadi_int casadi_s6[6] = {6, 1, 0, 2, 3, 4};
static const casadi_int casadi_s7[5] = {6, 1, 0, 1, 5};
static const casadi_int casadi_s8[8] = {6, 1, 0, 4, 0, 1, 2, 5};
static const casadi_int casadi_s9[25] = {6, 7, 0, 1, 2, 4, 7, 9, 11, 15, 4, 5, 0, 1, 0, 1, 2, 2, 3, 3, 4, 0, 1, 2, 5};
static const casadi_int casadi_s10[12] = {2, 7, 0, 1, 2, 2, 2, 2, 2, 2, 0, 1};
static const casadi_int casadi_s11[5] = {0, 7, 14, 20, 23};
static const casadi_int casadi_s12[4] = {0, 1, 2, 5};
static const casadi_int casadi_s13[4] = {1, 8, 15, 25};
static const casadi_int casadi_s14[3] = {3, 10, 16};
static const casadi_int casadi_s15[4] = {4, 11, 17, 21};
static const casadi_int casadi_s16[5] = {5, 12, 18, 22, 24};
static const casadi_int casadi_s17[4] = {6, 13, 19, 26};
static const casadi_int casadi_s18[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s19[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s20[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s21[36] = {8, 6, 0, 7, 14, 20, 23, 25, 27, 0, 1, 2, 4, 5, 6, 7, 0, 1, 3, 4, 5, 6, 7, 0, 1, 4, 5, 6, 7, 0, 5, 6, 0, 6, 1, 7};

/* f:(i0[6],i1[2])->(o0[6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #7: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #8: @1 = 0.6 */
  w1 = 5.9999999999999998e-01;
  /* #9: @1 = (@1*@0) */
  w1 *= w0;
  /* #10: @0 = 3.14159 */
  w0 = 3.1415926535897931e+00;
  /* #11: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #12: @0 = (@0+@2) */
  w0 += w2;
  /* #13: @2 = 2 */
  w2 = 2.;
  /* #14: @0 = (@0/@2) */
  w0 /= w2;
  /* #15: @0 = tan(@0) */
  w0 = tan( w0 );
  /* #16: @1 = (@1/@0) */
  w1 /= w0;
  /* #17: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #18: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #19: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #20: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #21: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #22: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #23: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  return 0;
}

/* fwd7_f:(i0[6],i1[2],out_o0[6x1,0nz],fwd_i0[6x7],fwd_i1[2x7])->(fwd_o0[6x7]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+19, w15, w16, w17;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 6, w2);
  /* #3: {NULL, NULL, @3, @4, @5, @6} = vertsplit(@2) */
  w3 = w2[2];
  w4 = w2[3];
  w5 = w2[4];
  w6 = w2[5];
  /* #4: @7 = (@1*@6) */
  w7  = (w1*w6);
  /* #5: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #6: @9 = sin(@0) */
  w9 = sin( w0 );
  /* #7: @10 = (@9*@3) */
  w10  = (w9*w3);
  /* #8: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #9: @7 = (@7-@10) */
  w7 -= w10;
  /* #10: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  /* #11: @7 = sin(@0) */
  w7 = sin( w0 );
  /* #12: @10 = (@7*@6) */
  w10  = (w7*w6);
  /* #13: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #14: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #15: @3 = (@8*@3) */
  w3  = (w8*w3);
  /* #16: @10 = (@10+@3) */
  w10 += w3;
  /* #17: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #18: @10 = 0.6 */
  w10 = 5.9999999999999998e-01;
  /* #19: @6 = (@10*@6) */
  w6  = (w10*w6);
  /* #20: @3 = 3.14159 */
  w3 = 3.1415926535897931e+00;
  /* #21: @11 = input[0][3] */
  w11 = arg[0] ? arg[0][3] : 0;
  /* #22: @3 = (@3+@11) */
  w3 += w11;
  /* #23: @11 = 2 */
  w11 = 2.;
  /* #24: @3 = (@3/@11) */
  w3 /= w11;
  /* #25: @11 = tan(@3) */
  w11 = tan( w3 );
  /* #26: @6 = (@6/@11) */
  w6 /= w11;
  /* #27: @12 = (@10*@8) */
  w12  = (w10*w8);
  /* #28: @12 = (@12/@11) */
  w12 /= w11;
  /* #29: @12 = (@12/@11) */
  w12 /= w11;
  /* #30: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #31: @4 = (@13*@4) */
  w4  = (w13*w4);
  /* #32: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #33: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #34: @4 = (@4/@3) */
  w4 /= w3;
  /* #35: @4 = (@12*@4) */
  w4  = (w12*w4);
  /* #36: @6 = (@6-@4) */
  w6 -= w4;
  /* #37: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #38: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #39: @14 = input[4][0] */
  casadi_copy(arg[4], 2, w14);
  /* #40: {@5, @6} = vertsplit(@14) */
  w5 = w14[0];
  w6 = w14[1];
  /* #41: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #42: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #43: @2 = input[3][1] */
  casadi_copy(arg[3] ? arg[3]+6 : 0, 6, w2);
  /* #44: {NULL, NULL, @6, @5, @4, @15} = vertsplit(@2) */
  w6 = w2[2];
  w5 = w2[3];
  w4 = w2[4];
  w15 = w2[5];
  /* #45: @16 = (@1*@15) */
  w16  = (w1*w15);
  /* #46: @17 = (@9*@6) */
  w17  = (w9*w6);
  /* #47: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #48: @16 = (@16-@17) */
  w16 -= w17;
  /* #49: output[0][6] = @16 */
  if (res[0]) res[0][6] = w16;
  /* #50: @16 = (@7*@15) */
  w16  = (w7*w15);
  /* #51: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #52: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #53: @16 = (@16+@6) */
  w16 += w6;
  /* #54: output[0][7] = @16 */
  if (res[0]) res[0][7] = w16;
  /* #55: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #56: @15 = (@15/@11) */
  w15 /= w11;
  /* #57: @5 = (@13*@5) */
  w5  = (w13*w5);
  /* #58: @5 = (@5/@3) */
  w5 /= w3;
  /* #59: @5 = (@12*@5) */
  w5  = (w12*w5);
  /* #60: @15 = (@15-@5) */
  w15 -= w5;
  /* #61: output[0][8] = @15 */
  if (res[0]) res[0][8] = w15;
  /* #62: output[0][9] = @4 */
  if (res[0]) res[0][9] = w4;
  /* #63: @14 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+2 : 0, 2, w14);
  /* #64: {@4, @15} = vertsplit(@14) */
  w4 = w14[0];
  w15 = w14[1];
  /* #65: output[0][10] = @4 */
  if (res[0]) res[0][10] = w4;
  /* #66: output[0][11] = @15 */
  if (res[0]) res[0][11] = w15;
  /* #67: @2 = input[3][2] */
  casadi_copy(arg[3] ? arg[3]+12 : 0, 6, w2);
  /* #68: {NULL, NULL, @15, @4, @5, @16} = vertsplit(@2) */
  w15 = w2[2];
  w4 = w2[3];
  w5 = w2[4];
  w16 = w2[5];
  /* #69: @6 = (@1*@16) */
  w6  = (w1*w16);
  /* #70: @17 = (@9*@15) */
  w17  = (w9*w15);
  /* #71: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #72: @6 = (@6-@17) */
  w6 -= w17;
  /* #73: output[0][12] = @6 */
  if (res[0]) res[0][12] = w6;
  /* #74: @6 = (@7*@16) */
  w6  = (w7*w16);
  /* #75: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #76: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #77: @6 = (@6+@15) */
  w6 += w15;
  /* #78: output[0][13] = @6 */
  if (res[0]) res[0][13] = w6;
  /* #79: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #80: @16 = (@16/@11) */
  w16 /= w11;
  /* #81: @4 = (@13*@4) */
  w4  = (w13*w4);
  /* #82: @4 = (@4/@3) */
  w4 /= w3;
  /* #83: @4 = (@12*@4) */
  w4  = (w12*w4);
  /* #84: @16 = (@16-@4) */
  w16 -= w4;
  /* #85: output[0][14] = @16 */
  if (res[0]) res[0][14] = w16;
  /* #86: output[0][15] = @5 */
  if (res[0]) res[0][15] = w5;
  /* #87: @14 = input[4][2] */
  casadi_copy(arg[4] ? arg[4]+4 : 0, 2, w14);
  /* #88: {@5, @16} = vertsplit(@14) */
  w5 = w14[0];
  w16 = w14[1];
  /* #89: output[0][16] = @5 */
  if (res[0]) res[0][16] = w5;
  /* #90: output[0][17] = @16 */
  if (res[0]) res[0][17] = w16;
  /* #91: @2 = input[3][3] */
  casadi_copy(arg[3] ? arg[3]+18 : 0, 6, w2);
  /* #92: {NULL, NULL, @16, @5, @4, @6} = vertsplit(@2) */
  w16 = w2[2];
  w5 = w2[3];
  w4 = w2[4];
  w6 = w2[5];
  /* #93: @15 = (@1*@6) */
  w15  = (w1*w6);
  /* #94: @17 = (@9*@16) */
  w17  = (w9*w16);
  /* #95: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #96: @15 = (@15-@17) */
  w15 -= w17;
  /* #97: output[0][18] = @15 */
  if (res[0]) res[0][18] = w15;
  /* #98: @15 = (@7*@6) */
  w15  = (w7*w6);
  /* #99: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #100: @16 = (@8*@16) */
  w16  = (w8*w16);
  /* #101: @15 = (@15+@16) */
  w15 += w16;
  /* #102: output[0][19] = @15 */
  if (res[0]) res[0][19] = w15;
  /* #103: @6 = (@10*@6) */
  w6  = (w10*w6);
  /* #104: @6 = (@6/@11) */
  w6 /= w11;
  /* #105: @5 = (@13*@5) */
  w5  = (w13*w5);
  /* #106: @5 = (@5/@3) */
  w5 /= w3;
  /* #107: @5 = (@12*@5) */
  w5  = (w12*w5);
  /* #108: @6 = (@6-@5) */
  w6 -= w5;
  /* #109: output[0][20] = @6 */
  if (res[0]) res[0][20] = w6;
  /* #110: output[0][21] = @4 */
  if (res[0]) res[0][21] = w4;
  /* #111: @14 = input[4][3] */
  casadi_copy(arg[4] ? arg[4]+6 : 0, 2, w14);
  /* #112: {@4, @6} = vertsplit(@14) */
  w4 = w14[0];
  w6 = w14[1];
  /* #113: output[0][22] = @4 */
  if (res[0]) res[0][22] = w4;
  /* #114: output[0][23] = @6 */
  if (res[0]) res[0][23] = w6;
  /* #115: @2 = input[3][4] */
  casadi_copy(arg[3] ? arg[3]+24 : 0, 6, w2);
  /* #116: {NULL, NULL, @6, @4, @5, @15} = vertsplit(@2) */
  w6 = w2[2];
  w4 = w2[3];
  w5 = w2[4];
  w15 = w2[5];
  /* #117: @16 = (@1*@15) */
  w16  = (w1*w15);
  /* #118: @17 = (@9*@6) */
  w17  = (w9*w6);
  /* #119: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #120: @16 = (@16-@17) */
  w16 -= w17;
  /* #121: output[0][24] = @16 */
  if (res[0]) res[0][24] = w16;
  /* #122: @16 = (@7*@15) */
  w16  = (w7*w15);
  /* #123: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #124: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #125: @16 = (@16+@6) */
  w16 += w6;
  /* #126: output[0][25] = @16 */
  if (res[0]) res[0][25] = w16;
  /* #127: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #128: @15 = (@15/@11) */
  w15 /= w11;
  /* #129: @4 = (@13*@4) */
  w4  = (w13*w4);
  /* #130: @4 = (@4/@3) */
  w4 /= w3;
  /* #131: @4 = (@12*@4) */
  w4  = (w12*w4);
  /* #132: @15 = (@15-@4) */
  w15 -= w4;
  /* #133: output[0][26] = @15 */
  if (res[0]) res[0][26] = w15;
  /* #134: output[0][27] = @5 */
  if (res[0]) res[0][27] = w5;
  /* #135: @14 = input[4][4] */
  casadi_copy(arg[4] ? arg[4]+8 : 0, 2, w14);
  /* #136: {@5, @15} = vertsplit(@14) */
  w5 = w14[0];
  w15 = w14[1];
  /* #137: output[0][28] = @5 */
  if (res[0]) res[0][28] = w5;
  /* #138: output[0][29] = @15 */
  if (res[0]) res[0][29] = w15;
  /* #139: @2 = input[3][5] */
  casadi_copy(arg[3] ? arg[3]+30 : 0, 6, w2);
  /* #140: {NULL, NULL, @15, @5, @4, @16} = vertsplit(@2) */
  w15 = w2[2];
  w5 = w2[3];
  w4 = w2[4];
  w16 = w2[5];
  /* #141: @6 = (@1*@16) */
  w6  = (w1*w16);
  /* #142: @17 = (@9*@15) */
  w17  = (w9*w15);
  /* #143: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #144: @6 = (@6-@17) */
  w6 -= w17;
  /* #145: output[0][30] = @6 */
  if (res[0]) res[0][30] = w6;
  /* #146: @6 = (@7*@16) */
  w6  = (w7*w16);
  /* #147: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #148: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #149: @6 = (@6+@15) */
  w6 += w15;
  /* #150: output[0][31] = @6 */
  if (res[0]) res[0][31] = w6;
  /* #151: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #152: @16 = (@16/@11) */
  w16 /= w11;
  /* #153: @5 = (@13*@5) */
  w5  = (w13*w5);
  /* #154: @5 = (@5/@3) */
  w5 /= w3;
  /* #155: @5 = (@12*@5) */
  w5  = (w12*w5);
  /* #156: @16 = (@16-@5) */
  w16 -= w5;
  /* #157: output[0][32] = @16 */
  if (res[0]) res[0][32] = w16;
  /* #158: output[0][33] = @4 */
  if (res[0]) res[0][33] = w4;
  /* #159: @14 = input[4][5] */
  casadi_copy(arg[4] ? arg[4]+10 : 0, 2, w14);
  /* #160: {@4, @16} = vertsplit(@14) */
  w4 = w14[0];
  w16 = w14[1];
  /* #161: output[0][34] = @4 */
  if (res[0]) res[0][34] = w4;
  /* #162: output[0][35] = @16 */
  if (res[0]) res[0][35] = w16;
  /* #163: @2 = input[3][6] */
  casadi_copy(arg[3] ? arg[3]+36 : 0, 6, w2);
  /* #164: {NULL, NULL, @16, @4, @5, @6} = vertsplit(@2) */
  w16 = w2[2];
  w4 = w2[3];
  w5 = w2[4];
  w6 = w2[5];
  /* #165: @1 = (@1*@6) */
  w1 *= w6;
  /* #166: @9 = (@9*@16) */
  w9 *= w16;
  /* #167: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #168: @1 = (@1-@9) */
  w1 -= w9;
  /* #169: output[0][36] = @1 */
  if (res[0]) res[0][36] = w1;
  /* #170: @7 = (@7*@6) */
  w7 *= w6;
  /* #171: @0 = (@0*@16) */
  w0 *= w16;
  /* #172: @8 = (@8*@0) */
  w8 *= w0;
  /* #173: @7 = (@7+@8) */
  w7 += w8;
  /* #174: output[0][37] = @7 */
  if (res[0]) res[0][37] = w7;
  /* #175: @10 = (@10*@6) */
  w10 *= w6;
  /* #176: @10 = (@10/@11) */
  w10 /= w11;
  /* #177: @13 = (@13*@4) */
  w13 *= w4;
  /* #178: @13 = (@13/@3) */
  w13 /= w3;
  /* #179: @12 = (@12*@13) */
  w12 *= w13;
  /* #180: @10 = (@10-@12) */
  w10 -= w12;
  /* #181: output[0][38] = @10 */
  if (res[0]) res[0][38] = w10;
  /* #182: output[0][39] = @5 */
  if (res[0]) res[0][39] = w5;
  /* #183: @14 = input[4][6] */
  casadi_copy(arg[4] ? arg[4]+12 : 0, 2, w14);
  /* #184: {@5, @10} = vertsplit(@14) */
  w5 = w14[0];
  w10 = w14[1];
  /* #185: output[0][40] = @5 */
  if (res[0]) res[0][40] = w5;
  /* #186: output[0][41] = @10 */
  if (res[0]) res[0][41] = w10;
  return 0;
}

/* avant_dyn_disc_phi_fun_jac:(i0[6],i1[2],i2[5])->(o0[6],o1[8x6,27nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+30, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w16=w+45, *w17=w+51, *w18=w+57, *w19=w+59, *w20=w+65, *w21=w+71, *w22=w+77, w30, w31, *w32=w+106, w33, w34, *w36=w+110, w37, *w38=w+114, *w39=w+116, *w40=w+118, *w41=w+121, *w42=w+123, *w43=w+125, *w44=w+129, *w45=w+132, *w46=w+136, *w47=w+151, *w48=w+193, *w49=w+207, *w50=w+249, *w51=w+255, *w52=w+261, *w53=w+267, *w54=w+273, *w55=w+279, *w56=w+285, *w57=w+291, *w58=w+297, *w59=w+303, *w60=w+309, *w61=w+315, *w62=w+321, *w63=w+327, *w64=w+333, *w65=w+339, *w66=w+345;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @0 = input[2][3] */
  w0 = arg[2] ? arg[2][3] : 0;
  /* #8: @1 = 6 */
  w1 = 6.;
  /* #9: @1 = (@0/@1) */
  w1  = (w0/w1);
  /* #10: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #11: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #12: @9 = sin(@2) */
  w9 = sin( w2 );
  /* #13: @10 = (@5*@9) */
  w10  = (w5*w9);
  /* #14: @11 = 0.6 */
  w11 = 5.9999999999999998e-01;
  /* #15: @12 = (@11*@5) */
  w12  = (w11*w5);
  /* #16: @13 = 3.14159 */
  w13 = 3.1415926535897931e+00;
  /* #17: @13 = (@13+@3) */
  w13 += w3;
  /* #18: @3 = 2 */
  w3 = 2.;
  /* #19: @13 = (@13/@3) */
  w13 /= w3;
  /* #20: @3 = tan(@13) */
  w3 = tan( w13 );
  /* #21: @12 = (@12/@3) */
  w12 /= w3;
  /* #22: @14 = input[1][0] */
  w14 = arg[1] ? arg[1][0] : 0;
  /* #23: @15 = input[1][1] */
  w15 = arg[1] ? arg[1][1] : 0;
  /* #24: @16 = vertcat(@8, @10, @12, @4, @14, @15) */
  rr=w16;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w14;
  *rr++ = w15;
  /* #25: @8 = 2 */
  w8 = 2.;
  /* #26: @8 = (@0/@8) */
  w8  = (w0/w8);
  /* #27: @17 = (@8*@16) */
  for (i=0, rr=w17, cs=w16; i<6; ++i) (*rr++)  = (w8*(*cs++));
  /* #28: @17 = (@6+@17) */
  for (i=0, rr=w17, cr=w6, cs=w17; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #29: @18 = vertcat(@14, @15) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  /* #30: @19 = f(@17, @18) */
  arg1[0]=w17;
  arg1[1]=w18;
  res1[0]=w19;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #31: @20 = (2.*@19) */
  for (i=0, rr=w20, cs=w19; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #32: @16 = (@16+@20) */
  for (i=0, rr=w16, cs=w20; i<6; ++i) (*rr++) += (*cs++);
  /* #33: @14 = 2 */
  w14 = 2.;
  /* #34: @14 = (@0/@14) */
  w14  = (w0/w14);
  /* #35: @19 = (@14*@19) */
  for (i=0, rr=w19, cs=w19; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #36: @19 = (@6+@19) */
  for (i=0, rr=w19, cr=w6, cs=w19; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #37: @20 = f(@19, @18) */
  arg1[0]=w19;
  arg1[1]=w18;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #38: @21 = (2.*@20) */
  for (i=0, rr=w21, cs=w20; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #39: @16 = (@16+@21) */
  for (i=0, rr=w16, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #40: @20 = (@0*@20) */
  for (i=0, rr=w20, cs=w20; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #41: @20 = (@6+@20) */
  for (i=0, rr=w20, cr=w6, cs=w20; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #42: @21 = f(@20, @18) */
  arg1[0]=w20;
  arg1[1]=w18;
  res1[0]=w21;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #43: @16 = (@16+@21) */
  for (i=0, rr=w16, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #44: @16 = (@1*@16) */
  for (i=0, rr=w16, cs=w16; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #45: @6 = (@6+@16) */
  for (i=0, rr=w6, cs=w16; i<6; ++i) (*rr++) += (*cs++);
  /* #46: output[0][0] = @6 */
  casadi_copy(w6, 6, res[0]);
  /* #47: @22 = zeros(8x6,27nz) */
  casadi_clear(w22, 27);
  /* #48: @23 = 00 */
  /* #49: @24 = 00 */
  /* #50: @25 = 00 */
  /* #51: @26 = 00 */
  /* #52: @15 = ones(8x1,1nz) */
  w15 = 1.;
  /* #53: {@10, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w10 = w15;
  /* #54: @27 = 00 */
  /* #55: @15 = vertcat(@23, @24, @25, @26, @10, @27) */
  rr=(&w15);
  *rr++ = w10;
  /* #56: @6 = dense(@15) */
  casadi_densify((&w15), casadi_s0, w6, 0);
  /* #57: @23 = zeros(6x1,0nz) */
  /* #58: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #59: @24 = 00 */
  /* #60: @25 = 00 */
  /* #61: @26 = 00 */
  /* #62: @28 = 00 */
  /* #63: @29 = 00 */
  /* #64: @4 = ones(8x1,1nz) */
  w4 = 1.;
  /* #65: {NULL, @30, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@4) */
  w30 = w4;
  /* #66: @4 = vertcat(@24, @25, @26, @28, @29, @30) */
  rr=(&w4);
  *rr++ = w30;
  /* #67: @31 = (@8*@4) */
  w31  = (w8*w4);
  /* #68: @32 = ones(8x1,2nz) */
  casadi_fill(w32, 2, 1.);
  /* #69: {NULL, NULL, @33, @34, NULL, NULL, NULL, NULL} = vertsplit(@32) */
  w33 = w32[0];
  w34 = w32[1];
  /* #70: @24 = 00 */
  /* #71: @25 = 00 */
  /* #72: @26 = 00 */
  /* #73: @28 = 00 */
  /* #74: @32 = vertcat(@33, @34, @24, @25, @26, @28) */
  rr=w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #75: @24 = 00 */
  /* #76: @25 = 00 */
  /* #77: @33 = ones(8x1,1nz) */
  w33 = 1.;
  /* #78: {NULL, NULL, NULL, NULL, @34, NULL, NULL, NULL} = vertsplit(@33) */
  w34 = w33;
  /* #79: @26 = 00 */
  /* #80: @28 = 00 */
  /* #81: @35 = 00 */
  /* #82: @33 = vertcat(@24, @25, @34, @26, @28, @35) */
  rr=(&w33);
  *rr++ = w34;
  /* #83: @36 = project(@33) */
  casadi_project((&w33), casadi_s1, w36, casadi_s2, w);
  /* #84: @37 = sin(@2) */
  w37 = sin( w2 );
  /* #85: @37 = (@37*@34) */
  w37 *= w34;
  /* #86: @37 = (@5*@37) */
  w37  = (w5*w37);
  /* #87: @37 = (-@37) */
  w37 = (- w37 );
  /* #88: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #89: @2 = (@2*@34) */
  w2 *= w34;
  /* #90: @5 = (@5*@2) */
  w5 *= w2;
  /* #91: @24 = 00 */
  /* #92: @25 = 00 */
  /* #93: @26 = 00 */
  /* #94: @38 = vertcat(@37, @5, @24, @28, @25, @26) */
  rr=w38;
  *rr++ = w37;
  *rr++ = w5;
  /* #95: @39 = (@8*@38) */
  for (i=0, rr=w39, cs=w38; i<2; ++i) (*rr++)  = (w8*(*cs++));
  /* #96: @40 = project(@39) */
  casadi_project(w39, casadi_s3, w40, casadi_s2, w);
  /* #97: @36 = (@36+@40) */
  for (i=0, rr=w36, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #98: @24 = 00 */
  /* #99: @28 = 00 */
  /* #100: @25 = 00 */
  /* #101: @37 = ones(8x1,1nz) */
  w37 = 1.;
  /* #102: {NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL} = vertsplit(@37) */
  w5 = w37;
  /* #103: @26 = 00 */
  /* #104: @35 = 00 */
  /* #105: @37 = vertcat(@24, @28, @25, @5, @26, @35) */
  rr=(&w37);
  *rr++ = w5;
  /* #106: @39 = project(@37) */
  casadi_project((&w37), casadi_s4, w39, casadi_s5, w);
  /* #107: @24 = 00 */
  /* #108: @28 = 00 */
  /* #109: @12 = (@12/@3) */
  w12 /= w3;
  /* #110: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #111: @2 = (@2*@5) */
  w2 *= w5;
  /* #112: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #113: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #114: @2 = (@2/@13) */
  w2 /= w13;
  /* #115: @12 = (@12*@2) */
  w12 *= w2;
  /* #116: @12 = (-@12) */
  w12 = (- w12 );
  /* #117: @25 = 00 */
  /* #118: @35 = 00 */
  /* #119: @2 = vertcat(@24, @28, @12, @26, @25, @35) */
  rr=(&w2);
  *rr++ = w12;
  /* #120: @12 = (@8*@2) */
  w12  = (w8*w2);
  /* #121: @41 = project(@12) */
  casadi_project((&w12), casadi_s1, w41, casadi_s5, w);
  /* #122: @39 = (@39+@41) */
  for (i=0, rr=w39, cs=w41; i<2; ++i) (*rr++) += (*cs++);
  /* #123: @24 = 00 */
  /* #124: @28 = 00 */
  /* #125: @26 = 00 */
  /* #126: @25 = 00 */
  /* #127: @12 = ones(8x1,1nz) */
  w12 = 1.;
  /* #128: {NULL, NULL, NULL, NULL, NULL, NULL, @13, NULL} = vertsplit(@12) */
  w13 = w12;
  /* #129: @35 = 00 */
  /* #130: @12 = vertcat(@24, @28, @26, @25, @13, @35) */
  rr=(&w12);
  *rr++ = w13;
  /* #131: @41 = project(@12) */
  casadi_project((&w12), casadi_s0, w41, casadi_s6, w);
  /* #132: @24 = 00 */
  /* #133: @28 = 00 */
  /* #134: @26 = 00 */
  /* #135: @25 = 00 */
  /* #136: @35 = 00 */
  /* #137: @5 = vertcat(@24, @28, @26, @13, @25, @35) */
  rr=(&w5);
  *rr++ = w13;
  /* #138: @13 = (@8*@5) */
  w13  = (w8*w5);
  /* #139: @42 = project(@13) */
  casadi_project((&w13), casadi_s4, w42, casadi_s6, w);
  /* #140: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<2; ++i) (*rr++) += (*cs++);
  /* #141: @24 = 00 */
  /* #142: @28 = 00 */
  /* #143: @26 = 00 */
  /* #144: @25 = 00 */
  /* #145: @35 = 00 */
  /* #146: @13 = ones(8x1,1nz) */
  w13 = 1.;
  /* #147: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @34} = vertsplit(@13) */
  w34 = w13;
  /* #148: @13 = vertcat(@24, @28, @26, @25, @35, @34) */
  rr=(&w13);
  *rr++ = w34;
  /* #149: @43 = project(@13) */
  casadi_project((&w13), casadi_s7, w43, casadi_s8, w);
  /* #150: @7 = (@7*@34) */
  w7 *= w34;
  /* #151: @9 = (@9*@34) */
  w9 *= w34;
  /* #152: @11 = (@11*@34) */
  w11 *= w34;
  /* #153: @11 = (@11/@3) */
  w11 /= w3;
  /* #154: @24 = 00 */
  /* #155: @28 = 00 */
  /* #156: @40 = vertcat(@7, @9, @11, @35, @24, @28) */
  rr=w40;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w11;
  /* #157: @44 = (@8*@40) */
  for (i=0, rr=w44, cs=w40; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #158: @45 = project(@44) */
  casadi_project(w44, casadi_s2, w45, casadi_s8, w);
  /* #159: @43 = (@43+@45) */
  for (i=0, rr=w43, cs=w45; i<4; ++i) (*rr++) += (*cs++);
  /* #160: @46 = horzcat(@15, @31, @32, @36, @39, @41, @43) */
  rr=w46;
  *rr++ = w15;
  *rr++ = w31;
  for (i=0, cs=w32; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<4; ++i) *rr++ = *cs++;
  /* #161: @47 = dense(@46) */
  casadi_densify(w46, casadi_s9, w47, 0);
  /* #162: @15 = vertcat(@10, @27) */
  rr=(&w15);
  *rr++ = w10;
  /* #163: @10 = vertcat(@29, @30) */
  rr=(&w10);
  *rr++ = w30;
  /* #164: @29 = zeros(2x1,0nz) */
  /* #165: @27 = zeros(2x1,0nz) */
  /* #166: @35 = zeros(2x1,0nz) */
  /* #167: @24 = zeros(2x1,0nz) */
  /* #168: @28 = zeros(2x1,0nz) */
  /* #169: @39 = horzcat(@15, @10, @29, @27, @35, @24, @28) */
  rr=w39;
  *rr++ = w15;
  *rr++ = w10;
  /* #170: @48 = dense(@39) */
  casadi_densify(w39, casadi_s10, w48, 0);
  /* #171: @49 = fwd7_f(@17, @18, @23, @47, @48) */
  arg1[0]=w17;
  arg1[1]=w18;
  arg1[2]=0;
  arg1[3]=w47;
  arg1[4]=w48;
  res1[0]=w49;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #172: {@17, @16, @21, @50, @51, @52, @53} = horzsplit(@49) */
  casadi_copy(w49, 6, w17);
  casadi_copy(w49+6, 6, w16);
  casadi_copy(w49+12, 6, w21);
  casadi_copy(w49+18, 6, w50);
  casadi_copy(w49+24, 6, w51);
  casadi_copy(w49+30, 6, w52);
  casadi_copy(w49+36, 6, w53);
  /* #173: @54 = (2.*@17) */
  for (i=0, rr=w54, cs=w17; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #174: @6 = (@6+@54) */
  for (i=0, rr=w6, cs=w54; i<6; ++i) (*rr++) += (*cs++);
  /* #175: @23 = zeros(6x1,0nz) */
  /* #176: @17 = (@14*@17) */
  for (i=0, rr=w17, cs=w17; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #177: @54 = (@14*@16) */
  for (i=0, rr=w54, cs=w16; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #178: @55 = dense(@32) */
  casadi_densify(w32, casadi_s3, w55, 0);
  /* #179: @56 = (@14*@21) */
  for (i=0, rr=w56, cs=w21; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #180: @55 = (@55+@56) */
  for (i=0, rr=w55, cs=w56; i<6; ++i) (*rr++) += (*cs++);
  /* #181: @56 = dense(@33) */
  casadi_densify((&w33), casadi_s1, w56, 0);
  /* #182: @57 = (@14*@50) */
  for (i=0, rr=w57, cs=w50; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #183: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<6; ++i) (*rr++) += (*cs++);
  /* #184: @57 = dense(@37) */
  casadi_densify((&w37), casadi_s4, w57, 0);
  /* #185: @58 = (@14*@51) */
  for (i=0, rr=w58, cs=w51; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #186: @57 = (@57+@58) */
  for (i=0, rr=w57, cs=w58; i<6; ++i) (*rr++) += (*cs++);
  /* #187: @58 = dense(@12) */
  casadi_densify((&w12), casadi_s0, w58, 0);
  /* #188: @59 = (@14*@52) */
  for (i=0, rr=w59, cs=w52; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #189: @58 = (@58+@59) */
  for (i=0, rr=w58, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #190: @59 = dense(@13) */
  casadi_densify((&w13), casadi_s7, w59, 0);
  /* #191: @60 = (@14*@53) */
  for (i=0, rr=w60, cs=w53; i<6; ++i) (*rr++)  = (w14*(*cs++));
  /* #192: @59 = (@59+@60) */
  for (i=0, rr=w59, cs=w60; i<6; ++i) (*rr++) += (*cs++);
  /* #193: @49 = horzcat(@17, @54, @55, @56, @57, @58, @59) */
  rr=w49;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w57; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w58; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<6; ++i) *rr++ = *cs++;
  /* #194: @39 = horzcat(@15, @10, @29, @27, @35, @24, @28) */
  rr=w39;
  *rr++ = w15;
  *rr++ = w10;
  /* #195: @48 = dense(@39) */
  casadi_densify(w39, casadi_s10, w48, 0);
  /* #196: @47 = fwd7_f(@19, @18, @23, @49, @48) */
  arg1[0]=w19;
  arg1[1]=w18;
  arg1[2]=0;
  arg1[3]=w49;
  arg1[4]=w48;
  res1[0]=w47;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #197: {@19, @17, @54, @55, @56, @57, @58} = horzsplit(@47) */
  casadi_copy(w47, 6, w19);
  casadi_copy(w47+6, 6, w17);
  casadi_copy(w47+12, 6, w54);
  casadi_copy(w47+18, 6, w55);
  casadi_copy(w47+24, 6, w56);
  casadi_copy(w47+30, 6, w57);
  casadi_copy(w47+36, 6, w58);
  /* #198: @59 = (2.*@19) */
  for (i=0, rr=w59, cs=w19; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #199: @6 = (@6+@59) */
  for (i=0, rr=w6, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #200: @23 = zeros(6x1,0nz) */
  /* #201: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #202: @59 = (@0*@17) */
  for (i=0, rr=w59, cs=w17; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #203: @60 = dense(@32) */
  casadi_densify(w32, casadi_s3, w60, 0);
  /* #204: @61 = (@0*@54) */
  for (i=0, rr=w61, cs=w54; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #205: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<6; ++i) (*rr++) += (*cs++);
  /* #206: @61 = dense(@33) */
  casadi_densify((&w33), casadi_s1, w61, 0);
  /* #207: @62 = (@0*@55) */
  for (i=0, rr=w62, cs=w55; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #208: @61 = (@61+@62) */
  for (i=0, rr=w61, cs=w62; i<6; ++i) (*rr++) += (*cs++);
  /* #209: @62 = dense(@37) */
  casadi_densify((&w37), casadi_s4, w62, 0);
  /* #210: @63 = (@0*@56) */
  for (i=0, rr=w63, cs=w56; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #211: @62 = (@62+@63) */
  for (i=0, rr=w62, cs=w63; i<6; ++i) (*rr++) += (*cs++);
  /* #212: @63 = dense(@12) */
  casadi_densify((&w12), casadi_s0, w63, 0);
  /* #213: @64 = (@0*@57) */
  for (i=0, rr=w64, cs=w57; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #214: @63 = (@63+@64) */
  for (i=0, rr=w63, cs=w64; i<6; ++i) (*rr++) += (*cs++);
  /* #215: @64 = dense(@13) */
  casadi_densify((&w13), casadi_s7, w64, 0);
  /* #216: @65 = (@0*@58) */
  for (i=0, rr=w65, cs=w58; i<6; ++i) (*rr++)  = (w0*(*cs++));
  /* #217: @64 = (@64+@65) */
  for (i=0, rr=w64, cs=w65; i<6; ++i) (*rr++) += (*cs++);
  /* #218: @47 = horzcat(@19, @59, @60, @61, @62, @63, @64) */
  rr=w47;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w60; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w61; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w63; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w64; i<6; ++i) *rr++ = *cs++;
  /* #219: @39 = horzcat(@15, @10, @29, @27, @35, @24, @28) */
  rr=w39;
  *rr++ = w15;
  *rr++ = w10;
  /* #220: @48 = dense(@39) */
  casadi_densify(w39, casadi_s10, w48, 0);
  /* #221: @49 = fwd7_f(@20, @18, @23, @47, @48) */
  arg1[0]=w20;
  arg1[1]=w18;
  arg1[2]=0;
  arg1[3]=w47;
  arg1[4]=w48;
  res1[0]=w49;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #222: {@20, @19, @59, @60, @61, @62, @63} = horzsplit(@49) */
  casadi_copy(w49, 6, w20);
  casadi_copy(w49+6, 6, w19);
  casadi_copy(w49+12, 6, w59);
  casadi_copy(w49+18, 6, w60);
  casadi_copy(w49+24, 6, w61);
  casadi_copy(w49+30, 6, w62);
  casadi_copy(w49+36, 6, w63);
  /* #223: @6 = (@6+@20) */
  for (i=0, rr=w6, cs=w20; i<6; ++i) (*rr++) += (*cs++);
  /* #224: @6 = (@1*@6) */
  for (i=0, rr=w6, cs=w6; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #225: @66 = @6[:5] */
  for (rr=w66, ss=w6+0; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #226: (@22[0, 7, 14, 20, 23] = @66) */
  for (cii=casadi_s11, rr=w22, ss=w66; cii!=casadi_s11+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #227: @6 = dense(@4) */
  casadi_densify((&w4), casadi_s7, w6, 0);
  /* #228: @16 = (2.*@16) */
  for (i=0, rr=w16, cs=w16; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #229: @6 = (@6+@16) */
  for (i=0, rr=w6, cs=w16; i<6; ++i) (*rr++) += (*cs++);
  /* #230: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #231: @6 = (@6+@17) */
  for (i=0, rr=w6, cs=w17; i<6; ++i) (*rr++) += (*cs++);
  /* #232: @6 = (@6+@19) */
  for (i=0, rr=w6, cs=w19; i<6; ++i) (*rr++) += (*cs++);
  /* #233: @6 = (@1*@6) */
  for (i=0, rr=w6, cs=w6; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #234: @43 = @6[0, 1, 2, 5] */
  for (cii=casadi_s12, rr=w43, ss=w6; cii!=casadi_s12+4; ++cii) *rr++ = ss[*cii];
  /* #235: (@22[1, 8, 15, 25] = @43) */
  for (cii=casadi_s13, rr=w22, ss=w43; cii!=casadi_s13+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #236: @6 = dense(@32) */
  casadi_densify(w32, casadi_s3, w6, 0);
  /* #237: @21 = (2.*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #238: @54 = (2.*@54) */
  for (i=0, rr=w54, cs=w54; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #239: @21 = (@21+@54) */
  for (i=0, rr=w21, cs=w54; i<6; ++i) (*rr++) += (*cs++);
  /* #240: @21 = (@21+@59) */
  for (i=0, rr=w21, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #241: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #242: @6 = (@6+@21) */
  for (i=0, rr=w6, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #243: @32 = @6[:2] */
  for (rr=w32, ss=w6+0; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #244: (@22[2:16:7] = @32) */
  for (rr=w22+2, ss=w32; rr!=w22+16; rr+=7) *rr = *ss++;
  /* #245: @6 = dense(@33) */
  casadi_densify((&w33), casadi_s1, w6, 0);
  /* #246: @21 = dense(@38) */
  casadi_densify(w38, casadi_s3, w21, 0);
  /* #247: @50 = (2.*@50) */
  for (i=0, rr=w50, cs=w50; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #248: @21 = (@21+@50) */
  for (i=0, rr=w21, cs=w50; i<6; ++i) (*rr++) += (*cs++);
  /* #249: @55 = (2.*@55) */
  for (i=0, rr=w55, cs=w55; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #250: @21 = (@21+@55) */
  for (i=0, rr=w21, cs=w55; i<6; ++i) (*rr++) += (*cs++);
  /* #251: @21 = (@21+@60) */
  for (i=0, rr=w21, cs=w60; i<6; ++i) (*rr++) += (*cs++);
  /* #252: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #253: @6 = (@6+@21) */
  for (i=0, rr=w6, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #254: @36 = @6[:3] */
  for (rr=w36, ss=w6+0; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #255: (@22[3, 10, 16] = @36) */
  for (cii=casadi_s14, rr=w22, ss=w36; cii!=casadi_s14+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #256: @6 = dense(@37) */
  casadi_densify((&w37), casadi_s4, w6, 0);
  /* #257: @21 = dense(@2) */
  casadi_densify((&w2), casadi_s1, w21, 0);
  /* #258: @51 = (2.*@51) */
  for (i=0, rr=w51, cs=w51; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #259: @21 = (@21+@51) */
  for (i=0, rr=w21, cs=w51; i<6; ++i) (*rr++) += (*cs++);
  /* #260: @56 = (2.*@56) */
  for (i=0, rr=w56, cs=w56; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #261: @21 = (@21+@56) */
  for (i=0, rr=w21, cs=w56; i<6; ++i) (*rr++) += (*cs++);
  /* #262: @21 = (@21+@61) */
  for (i=0, rr=w21, cs=w61; i<6; ++i) (*rr++) += (*cs++);
  /* #263: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #264: @6 = (@6+@21) */
  for (i=0, rr=w6, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #265: @43 = @6[:4] */
  for (rr=w43, ss=w6+0; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #266: (@22[4, 11, 17, 21] = @43) */
  for (cii=casadi_s15, rr=w22, ss=w43; cii!=casadi_s15+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #267: @6 = dense(@12) */
  casadi_densify((&w12), casadi_s0, w6, 0);
  /* #268: @21 = dense(@5) */
  casadi_densify((&w5), casadi_s4, w21, 0);
  /* #269: @52 = (2.*@52) */
  for (i=0, rr=w52, cs=w52; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #270: @21 = (@21+@52) */
  for (i=0, rr=w21, cs=w52; i<6; ++i) (*rr++) += (*cs++);
  /* #271: @57 = (2.*@57) */
  for (i=0, rr=w57, cs=w57; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #272: @21 = (@21+@57) */
  for (i=0, rr=w21, cs=w57; i<6; ++i) (*rr++) += (*cs++);
  /* #273: @21 = (@21+@62) */
  for (i=0, rr=w21, cs=w62; i<6; ++i) (*rr++) += (*cs++);
  /* #274: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #275: @6 = (@6+@21) */
  for (i=0, rr=w6, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #276: @66 = @6[:5] */
  for (rr=w66, ss=w6+0; ss!=w6+5; ss+=1) *rr++ = *ss;
  /* #277: (@22[5, 12, 18, 22, 24] = @66) */
  for (cii=casadi_s16, rr=w22, ss=w66; cii!=casadi_s16+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #278: @6 = dense(@13) */
  casadi_densify((&w13), casadi_s7, w6, 0);
  /* #279: @21 = dense(@40) */
  casadi_densify(w40, casadi_s2, w21, 0);
  /* #280: @53 = (2.*@53) */
  for (i=0, rr=w53, cs=w53; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #281: @21 = (@21+@53) */
  for (i=0, rr=w21, cs=w53; i<6; ++i) (*rr++) += (*cs++);
  /* #282: @58 = (2.*@58) */
  for (i=0, rr=w58, cs=w58; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #283: @21 = (@21+@58) */
  for (i=0, rr=w21, cs=w58; i<6; ++i) (*rr++) += (*cs++);
  /* #284: @21 = (@21+@63) */
  for (i=0, rr=w21, cs=w63; i<6; ++i) (*rr++) += (*cs++);
  /* #285: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #286: @6 = (@6+@21) */
  for (i=0, rr=w6, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #287: @43 = @6[0, 1, 2, 5] */
  for (cii=casadi_s12, rr=w43, ss=w6; cii!=casadi_s12+4; ++cii) *rr++ = ss[*cii];
  /* #288: (@22[6, 13, 19, 26] = @43) */
  for (cii=casadi_s17, rr=w22, ss=w43; cii!=casadi_s17+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #289: output[1][0] = @22 */
  casadi_copy(w22, 27, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int avant_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real avant_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 350;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
