/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[11] = {6, 3, 0, 1, 2, 5, 0, 1, 0, 1, 2};
static const casadi_int casadi_s5[3] = {3, 0, 0};

/* avant_cost_y_e_fun_jac_ut_xt:(i0[6],i1[],i2[],i3[],i4[5])->(o0[3],o1[6x3,5nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, *w9=w+13, w11, *w12=w+18, *w13=w+20;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[4][0] */
  w1 = arg[4] ? arg[4][0] : 0;
  /* #2: @2 = (@0-@1) */
  w2  = (w0-w1);
  /* #3: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #4: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #5: @3 = input[4][1] */
  w3 = arg[4] ? arg[4][1] : 0;
  /* #6: @4 = (@2-@3) */
  w4  = (w2-w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @0 = (@0-@1) */
  w0 -= w1;
  /* #9: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #10: @2 = (@2-@3) */
  w2 -= w3;
  /* #11: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #12: @1 = (@1+@3) */
  w1 += w3;
  /* #13: @3 = 1.75 */
  w3 = 1.7500000000000000e+00;
  /* #14: @1 = (@1/@3) */
  w1 /= w3;
  /* #15: @3 = sq(@1) */
  w3 = casadi_sq( w1 );
  /* #16: @3 = (-@3) */
  w3 = (- w3 );
  /* #17: @3 = exp(@3) */
  w3 = exp( w3 );
  /* #18: @4 = 90 */
  w4 = 90.;
  /* #19: @5 = 1 */
  w5 = 1.;
  /* #20: @6 = input[4][2] */
  w6 = arg[4] ? arg[4][2] : 0;
  /* #21: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #22: @6 = (@6-@7) */
  w6 -= w7;
  /* #23: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #24: @5 = (@5-@7) */
  w5 -= w7;
  /* #25: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #26: @7 = (@3*@5) */
  w7  = (w3*w5);
  /* #27: output[0][2] = @7 */
  if (res[0]) res[0][2] = w7;
  /* #28: @8 = zeros(6x3,5nz) */
  casadi_clear(w8, 5);
  /* #29: @9 = ones(6x1,4nz) */
  casadi_fill(w9, 4, 1.);
  /* #30: {@7, NULL, NULL, NULL, NULL, NULL} = vertsplit(@9) */
  w7 = w9[0];
  /* #31: @10 = 00 */
  /* #32: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #33: @11 = 0.571429 */
  w11 = 5.7142857142857140e-01;
  /* #34: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #35: @0 = (@0*@7) */
  w0 *= w7;
  /* #36: @0 = (@11*@0) */
  w0  = (w11*w0);
  /* #37: @0 = (@1*@0) */
  w0  = (w1*w0);
  /* #38: @0 = (@3*@0) */
  w0  = (w3*w0);
  /* #39: @0 = (@5*@0) */
  w0  = (w5*w0);
  /* #40: @0 = (-@0) */
  w0 = (- w0 );
  /* #41: @12 = vertcat(@7, @10, @0) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w0;
  /* #42: @13 = @12[:2] */
  for (rr=w13, ss=w12+0; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #43: (@8[:4:2] = @13) */
  for (rr=w8+0, ss=w13; rr!=w8+4; rr+=2) *rr = *ss++;
  /* #44: @10 = 00 */
  /* #45: @7 = ones(6x1,1nz) */
  w7 = 1.;
  /* #46: {NULL, @0, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w0 = w7;
  /* #47: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #48: @2 = (@2*@0) */
  w2 *= w0;
  /* #49: @11 = (@11*@2) */
  w11 *= w2;
  /* #50: @1 = (@1*@11) */
  w1 *= w11;
  /* #51: @1 = (@3*@1) */
  w1  = (w3*w1);
  /* #52: @5 = (@5*@1) */
  w5 *= w1;
  /* #53: @5 = (-@5) */
  w5 = (- w5 );
  /* #54: @13 = vertcat(@10, @0, @5) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w5;
  /* #55: @12 = @13[:2] */
  for (rr=w12, ss=w13+0; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #56: (@8[1:5:2] = @12) */
  for (rr=w8+1, ss=w12; rr!=w8+5; rr+=2) *rr = *ss++;
  /* #57: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #58: @0 = ones(6x1,1nz) */
  w0 = 1.;
  /* #59: {NULL, NULL, @5, NULL, NULL, NULL} = vertsplit(@0) */
  w5 = w0;
  /* #60: @6 = (@6*@5) */
  w6 *= w5;
  /* #61: @4 = (@4*@6) */
  w4 *= w6;
  /* #62: @3 = (@3*@4) */
  w3 *= w4;
  /* #63: @3 = (-@3) */
  w3 = (- w3 );
  /* #64: (@8[4] = @3) */
  for (rr=w8+4, ss=(&w3); rr!=w8+5; rr+=1) *rr = *ss++;
  /* #65: output[1][0] = @8 */
  casadi_copy(w8, 5, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real avant_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 22;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
