/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[7] = {0, 2, 5, 7, 8, 9, 10};
static const casadi_int casadi_s1[4] = {1, 3, 6, 11};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[3] = {0, 0, 0};
static const casadi_int casadi_s5[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[24] = {8, 8, 0, 1, 2, 5, 7, 8, 9, 10, 13, 2, 3, 2, 3, 4, 2, 3, 1, 0, 7, 2, 3, 6};
static const casadi_int casadi_s8[3] = {8, 0, 0};

/* avant_cost_y_fun_jac_ut_xt:(i0[6],i1[2],i2[],i3[],i4[5])->(o0[8],o1[8x8,13nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+25, *w26=w+33, *w27=w+46, *w29=w+51, *w30=w+58, *w34=w+65, *w35=w+69, *w36=w+73, *w39=w+75;
  /* #0: @0 = input[4][4] */
  w0 = arg[4] ? arg[4][4] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[4][0] */
  w2 = arg[4] ? arg[4][0] : 0;
  /* #3: @3 = (@1-@2) */
  w3  = (w1-w2);
  /* #4: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[4][1] */
  w5 = arg[4] ? arg[4][1] : 0;
  /* #6: @6 = (@4-@5) */
  w6  = (w4-w5);
  /* #7: @7 = (@1-@2) */
  w7  = (w1-w2);
  /* #8: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #9: @9 = (@4-@5) */
  w9  = (w4-w5);
  /* #10: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #11: @8 = (@8+@10) */
  w8 += w10;
  /* #12: @10 = 1.75 */
  w10 = 1.7500000000000000e+00;
  /* #13: @8 = (@8/@10) */
  w8 /= w10;
  /* #14: @10 = sq(@8) */
  w10 = casadi_sq( w8 );
  /* #15: @10 = (-@10) */
  w10 = (- w10 );
  /* #16: @10 = exp(@10) */
  w10 = exp( w10 );
  /* #17: @11 = 90 */
  w11 = 90.;
  /* #18: @12 = 1 */
  w12 = 1.;
  /* #19: @13 = input[4][2] */
  w13 = arg[4] ? arg[4][2] : 0;
  /* #20: @14 = input[0][2] */
  w14 = arg[0] ? arg[0][2] : 0;
  /* #21: @14 = (@13-@14) */
  w14  = (w13-w14);
  /* #22: @15 = cos(@14) */
  w15 = cos( w14 );
  /* #23: @12 = (@12-@15) */
  w12 -= w15;
  /* #24: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #25: @15 = (@10*@12) */
  w15  = (w10*w12);
  /* #26: @16 = 25 */
  w16 = 25.;
  /* #27: @17 = 1 */
  w17 = 1.;
  /* #28: @1 = (@1-@2) */
  w1 -= w2;
  /* #29: @2 = cos(@13) */
  w2 = cos( w13 );
  /* #30: @1 = (@1*@2) */
  w1 *= w2;
  /* #31: @4 = (@4-@5) */
  w4 -= w5;
  /* #32: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #33: @4 = (@4*@13) */
  w4 *= w13;
  /* #34: @1 = (@1+@4) */
  w1 += w4;
  /* #35: @4 = 25 */
  w4 = 25.;
  /* #36: @1 = (@1-@4) */
  w1 -= w4;
  /* #37: @4 = 10 */
  w4 = 10.;
  /* #38: @1 = (@1/@4) */
  w1 /= w4;
  /* #39: @1 = tanh(@1) */
  w1 = tanh( w1 );
  /* #40: @17 = (@17+@1) */
  w17 += w1;
  /* #41: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #42: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #43: @5 = 180 */
  w5 = 180.;
  /* #44: @18 = input[1][0] */
  w18 = arg[1] ? arg[1][0] : 0;
  /* #45: @18 = (@5*@18) */
  w18  = (w5*w18);
  /* #46: @19 = 3.14159 */
  w19 = 3.1415926535897931e+00;
  /* #47: @18 = (@18/@19) */
  w18 /= w19;
  /* #48: @19 = 5 */
  w19 = 5.;
  /* #49: @18 = (@18/@19) */
  w18 /= w19;
  /* #50: @19 = input[0][5] */
  w19 = arg[0] ? arg[0][5] : 0;
  /* #51: @20 = 180 */
  w20 = 180.;
  /* #52: @21 = (@20*@10) */
  w21  = (w20*w10);
  /* #53: @22 = 3.14159 */
  w22 = 3.1415926535897931e+00;
  /* #54: @21 = (@21/@22) */
  w21 /= w22;
  /* #55: @22 = input[0][4] */
  w22 = arg[0] ? arg[0][4] : 0;
  /* #56: @23 = (@21*@22) */
  w23  = (w21*w22);
  /* #57: @24 = 5 */
  w24 = 5.;
  /* #58: @23 = (@23/@24) */
  w23 /= w24;
  /* #59: @25 = vertcat(@3, @6, @15, @17, @4, @18, @19, @23) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w4;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w23;
  /* #60: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #61: output[0][0] = @25 */
  casadi_copy(w25, 8, res[0]);
  /* #62: @26 = zeros(8x8,13nz) */
  casadi_clear(w26, 13);
  /* #63: @27 = ones(8x1,5nz) */
  casadi_fill(w27, 5, 1.);
  /* #64: {@3, @6, @15, NULL, NULL, NULL, NULL, @17} = vertsplit(@27) */
  w3 = w27[0];
  w6 = w27[1];
  w15 = w27[2];
  w17 = w27[4];
  /* #65: @28 = 00 */
  /* #66: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #67: @4 = 0.571429 */
  w4 = 5.7142857142857140e-01;
  /* #68: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #69: @7 = (@7*@15) */
  w7 *= w15;
  /* #70: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #71: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #72: @7 = (@10*@7) */
  w7  = (w10*w7);
  /* #73: @18 = (@12*@7) */
  w18  = (w12*w7);
  /* #74: @18 = (-@18) */
  w18 = (- w18 );
  /* #75: @19 = 1 */
  w19 = 1.;
  /* #76: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #77: @19 = (@19-@1) */
  w19 -= w1;
  /* #78: @1 = 0.1 */
  w1 = 1.0000000000000001e-01;
  /* #79: @2 = (@2*@15) */
  w2 *= w15;
  /* #80: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #81: @2 = (@19*@2) */
  w2  = (w19*w2);
  /* #82: @2 = (@16*@2) */
  w2  = (w16*w2);
  /* #83: @23 = 0.2 */
  w23 = 2.0000000000000001e-01;
  /* #84: @24 = 0.31831 */
  w24 = 3.1830988618379069e-01;
  /* #85: @5 = (@5*@3) */
  w5 *= w3;
  /* #86: @24 = (@24*@5) */
  w24 *= w5;
  /* #87: @23 = (@23*@24) */
  w23 *= w24;
  /* #88: @24 = 0.2 */
  w24 = 2.0000000000000001e-01;
  /* #89: @5 = 0.31831 */
  w5 = 3.1830988618379069e-01;
  /* #90: @7 = (@20*@7) */
  w7  = (w20*w7);
  /* #91: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #92: @7 = (@22*@7) */
  w7  = (w22*w7);
  /* #93: @7 = (@24*@7) */
  w7  = (w24*w7);
  /* #94: @7 = (-@7) */
  w7 = (- w7 );
  /* #95: @29 = vertcat(@15, @28, @18, @2, @6, @23, @17, @7) */
  rr=w29;
  *rr++ = w15;
  *rr++ = w18;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w23;
  *rr++ = w17;
  *rr++ = w7;
  /* #96: @29 = (@0*@29) */
  for (i=0, rr=w29, cs=w29; i<7; ++i) (*rr++)  = (w0*(*cs++));
  /* #97: @30 = @29[:7] */
  for (rr=w30, ss=w29+0; ss!=w29+7; ss+=1) *rr++ = *ss;
  /* #98: (@26[0, 2, 5, 7, 8, 9, 10] = @30) */
  for (cii=casadi_s0, rr=w26, ss=w30; cii!=casadi_s0+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #99: @28 = 00 */
  /* #100: @15 = ones(8x1,1nz) */
  w15 = 1.;
  /* #101: {NULL, NULL, NULL, @18, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w18 = w15;
  /* #102: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #103: @9 = (@9*@18) */
  w9 *= w18;
  /* #104: @4 = (@4*@9) */
  w4 *= w9;
  /* #105: @8 = (@8*@4) */
  w8 *= w4;
  /* #106: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #107: @12 = (@12*@8) */
  w12 *= w8;
  /* #108: @12 = (-@12) */
  w12 = (- w12 );
  /* #109: @13 = (@13*@18) */
  w13 *= w18;
  /* #110: @1 = (@1*@13) */
  w1 *= w13;
  /* #111: @19 = (@19*@1) */
  w19 *= w1;
  /* #112: @16 = (@16*@19) */
  w16 *= w19;
  /* #113: @31 = 00 */
  /* #114: @32 = 00 */
  /* #115: @33 = 00 */
  /* #116: @20 = (@20*@8) */
  w20 *= w8;
  /* #117: @5 = (@5*@20) */
  w5 *= w20;
  /* #118: @22 = (@22*@5) */
  w22 *= w5;
  /* #119: @22 = (@24*@22) */
  w22  = (w24*w22);
  /* #120: @22 = (-@22) */
  w22 = (- w22 );
  /* #121: @34 = vertcat(@28, @18, @12, @16, @31, @32, @33, @22) */
  rr=w34;
  *rr++ = w18;
  *rr++ = w12;
  *rr++ = w16;
  *rr++ = w22;
  /* #122: @34 = (@0*@34) */
  for (i=0, rr=w34, cs=w34; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #123: @35 = @34[:4] */
  for (rr=w35, ss=w34+0; ss!=w34+4; ss+=1) *rr++ = *ss;
  /* #124: (@26[1, 3, 6, 11] = @35) */
  for (cii=casadi_s1, rr=w26, ss=w35; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #125: @28 = 00 */
  /* #126: @31 = 00 */
  /* #127: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #128: @36 = ones(8x1,2nz) */
  casadi_fill(w36, 2, 1.);
  /* #129: {NULL, NULL, NULL, NULL, @18, NULL, @12, NULL} = vertsplit(@36) */
  w18 = w36[0];
  w12 = w36[1];
  /* #130: @14 = (@14*@18) */
  w14 *= w18;
  /* #131: @11 = (@11*@14) */
  w11 *= w14;
  /* #132: @10 = (@10*@11) */
  w10 *= w11;
  /* #133: @10 = (-@10) */
  w10 = (- w10 );
  /* #134: @32 = 00 */
  /* #135: @33 = 00 */
  /* #136: @37 = 00 */
  /* #137: @38 = 00 */
  /* #138: @21 = (@21*@12) */
  w21 *= w12;
  /* #139: @24 = (@24*@21) */
  w24 *= w21;
  /* #140: @36 = vertcat(@28, @31, @10, @32, @33, @37, @38, @24) */
  rr=w36;
  *rr++ = w10;
  *rr++ = w24;
  /* #141: @36 = (@0*@36) */
  for (i=0, rr=w36, cs=w36; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #142: @39 = @36[:2] */
  for (rr=w39, ss=w36+0; ss!=w36+2; ss+=1) *rr++ = *ss;
  /* #143: (@26[4:20:8] = @39) */
  for (rr=w26+4, ss=w39; rr!=w26+20; rr+=8) *rr = *ss++;
  /* #144: output[1][0] = @26 */
  casadi_copy(w26, 13, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real avant_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 77;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
