/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};

/* avant_cost_y_0_fun:(i0[6],i1[2],i2[],i3[],i4[5])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+12;
  /* #0: @0 = input[4][4] */
  w0 = arg[4] ? arg[4][4] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[4][0] */
  w2 = arg[4] ? arg[4][0] : 0;
  /* #3: @3 = (@1-@2) */
  w3  = (w1-w2);
  /* #4: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[4][1] */
  w5 = arg[4] ? arg[4][1] : 0;
  /* #6: @6 = (@4-@5) */
  w6  = (w4-w5);
  /* #7: @7 = (@1-@2) */
  w7  = (w1-w2);
  /* #8: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #9: @8 = (@4-@5) */
  w8  = (w4-w5);
  /* #10: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #11: @7 = (@7+@8) */
  w7 += w8;
  /* #12: @8 = 1.75 */
  w8 = 1.7500000000000000e+00;
  /* #13: @7 = (@7/@8) */
  w7 /= w8;
  /* #14: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #15: @7 = (-@7) */
  w7 = (- w7 );
  /* #16: @7 = exp(@7) */
  w7 = exp( w7 );
  /* #17: @8 = 90 */
  w8 = 90.;
  /* #18: @9 = 1 */
  w9 = 1.;
  /* #19: @10 = input[4][2] */
  w10 = arg[4] ? arg[4][2] : 0;
  /* #20: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #21: @11 = (@10-@11) */
  w11  = (w10-w11);
  /* #22: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #23: @9 = (@9-@11) */
  w9 -= w11;
  /* #24: @8 = (@8*@9) */
  w8 *= w9;
  /* #25: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #26: @9 = 25 */
  w9 = 25.;
  /* #27: @11 = 1 */
  w11 = 1.;
  /* #28: @1 = (@1-@2) */
  w1 -= w2;
  /* #29: @2 = cos(@10) */
  w2 = cos( w10 );
  /* #30: @1 = (@1*@2) */
  w1 *= w2;
  /* #31: @4 = (@4-@5) */
  w4 -= w5;
  /* #32: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #33: @4 = (@4*@10) */
  w4 *= w10;
  /* #34: @1 = (@1+@4) */
  w1 += w4;
  /* #35: @4 = 25 */
  w4 = 25.;
  /* #36: @1 = (@1-@4) */
  w1 -= w4;
  /* #37: @4 = 10 */
  w4 = 10.;
  /* #38: @1 = (@1/@4) */
  w1 /= w4;
  /* #39: @1 = tanh(@1) */
  w1 = tanh( w1 );
  /* #40: @11 = (@11+@1) */
  w11 += w1;
  /* #41: @9 = (@9*@11) */
  w9 *= w11;
  /* #42: @11 = input[1][1] */
  w11 = arg[1] ? arg[1][1] : 0;
  /* #43: @1 = 180 */
  w1 = 180.;
  /* #44: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #45: @1 = (@1*@4) */
  w1 *= w4;
  /* #46: @4 = 3.14159 */
  w4 = 3.1415926535897931e+00;
  /* #47: @1 = (@1/@4) */
  w1 /= w4;
  /* #48: @4 = 5 */
  w4 = 5.;
  /* #49: @1 = (@1/@4) */
  w1 /= w4;
  /* #50: @4 = input[0][5] */
  w4 = arg[0] ? arg[0][5] : 0;
  /* #51: @10 = 180 */
  w10 = 180.;
  /* #52: @10 = (@10*@7) */
  w10 *= w7;
  /* #53: @7 = 3.14159 */
  w7 = 3.1415926535897931e+00;
  /* #54: @10 = (@10/@7) */
  w10 /= w7;
  /* #55: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #56: @10 = (@10*@7) */
  w10 *= w7;
  /* #57: @7 = 5 */
  w7 = 5.;
  /* #58: @10 = (@10/@7) */
  w10 /= w7;
  /* #59: @12 = vertcat(@3, @6, @8, @9, @11, @1, @4, @10) */
  rr=w12;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w1;
  *rr++ = w4;
  *rr++ = w10;
  /* #60: @12 = (@0*@12) */
  for (i=0, rr=w12, cs=w12; i<8; ++i) (*rr++)  = (w0*(*cs++));
  /* #61: output[0][0] = @12 */
  casadi_copy(w12, 8, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real avant_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 20;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
