/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[18] = {6, 6, 0, 3, 6, 9, 9, 9, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* avant_cost_y_e_hess:(i0[6],i1[],i2[],i3[3],i4[],i5[5])->(o0[6x6,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, *w11=w+19, w12, w13, *w14=w+24, w15, w16, w17, w18, w19, w20, *w24=w+34, *w25=w+37;
  /* #0: @0 = zeros(6x6,9nz) */
  casadi_clear(w0, 9);
  /* #1: @1 = 0.571429 */
  w1 = 5.7142857142857140e-01;
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[5][0] */
  w3 = arg[5] ? arg[5][0] : 0;
  /* #4: @2 = (@2-@3) */
  w2 -= w3;
  /* #5: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #6: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #7: @5 = input[5][1] */
  w5 = arg[5] ? arg[5][1] : 0;
  /* #8: @4 = (@4-@5) */
  w4 -= w5;
  /* #9: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #10: @3 = (@3+@5) */
  w3 += w5;
  /* #11: @5 = 1.75 */
  w5 = 1.7500000000000000e+00;
  /* #12: @3 = (@3/@5) */
  w3 /= w5;
  /* #13: @5 = (2.*@3) */
  w5 = (2.* w3 );
  /* #14: @6 = sq(@3) */
  w6 = casadi_sq( w3 );
  /* #15: @6 = (-@6) */
  w6 = (- w6 );
  /* #16: @6 = exp(@6) */
  w6 = exp( w6 );
  /* #17: @7 = 90 */
  w7 = 90.;
  /* #18: @8 = 1 */
  w8 = 1.;
  /* #19: @9 = input[5][2] */
  w9 = arg[5] ? arg[5][2] : 0;
  /* #20: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #21: @9 = (@9-@10) */
  w9 -= w10;
  /* #22: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #23: @8 = (@8-@10) */
  w8 -= w10;
  /* #24: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #25: @11 = input[3][0] */
  casadi_copy(arg[3], 3, w11);
  /* #26: {NULL, NULL, @10} = vertsplit(@11) */
  w10 = w11[2];
  /* #27: @8 = (@8*@10) */
  w8 *= w10;
  /* #28: @12 = (@6*@8) */
  w12  = (w6*w8);
  /* #29: @13 = (@5*@12) */
  w13  = (w5*w12);
  /* #30: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #31: @14 = ones(6x1,4nz) */
  casadi_fill(w14, 4, 1.);
  /* #32: {@15, NULL, NULL, NULL, NULL, NULL} = vertsplit(@14) */
  w15 = w14[0];
  /* #33: @16 = (2.*@15) */
  w16 = (2.* w15 );
  /* #34: @16 = (@13*@16) */
  w16  = (w13*w16);
  /* #35: @17 = (2.*@2) */
  w17 = (2.* w2 );
  /* #36: @18 = 0.571429 */
  w18 = 5.7142857142857140e-01;
  /* #37: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #38: @2 = (@2*@15) */
  w2 *= w15;
  /* #39: @2 = (@18*@2) */
  w2  = (w18*w2);
  /* #40: @15 = (2.*@2) */
  w15 = (2.* w2 );
  /* #41: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #42: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #43: @2 = (@3*@2) */
  w2  = (w3*w2);
  /* #44: @2 = (@6*@2) */
  w2  = (w6*w2);
  /* #45: @19 = (@8*@2) */
  w19  = (w8*w2);
  /* #46: @19 = (@5*@19) */
  w19  = (w5*w19);
  /* #47: @15 = (@15-@19) */
  w15 -= w19;
  /* #48: @15 = (@1*@15) */
  w15  = (w1*w15);
  /* #49: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #50: @16 = (@16+@19) */
  w16 += w19;
  /* #51: @16 = (-@16) */
  w16 = (- w16 );
  /* #52: @19 = (2.*@4) */
  w19 = (2.* w4 );
  /* #53: @15 = (@19*@15) */
  w15  = (w19*w15);
  /* #54: @15 = (-@15) */
  w15 = (- w15 );
  /* #55: @20 = sin(@9) */
  w20 = sin( w9 );
  /* #56: @2 = (@10*@2) */
  w2  = (w10*w2);
  /* #57: @2 = (@7*@2) */
  w2  = (w7*w2);
  /* #58: @2 = (@20*@2) */
  w2  = (w20*w2);
  /* #59: @21 = 00 */
  /* #60: @22 = 00 */
  /* #61: @23 = 00 */
  /* #62: @11 = vertcat(@16, @15, @2, @21, @22, @23) */
  rr=w11;
  *rr++ = w16;
  *rr++ = w15;
  *rr++ = w2;
  /* #63: @24 = @11[:3] */
  for (rr=w24, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #64: (@0[:9:3] = @24) */
  for (rr=w0+0, ss=w24; rr!=w0+9; rr+=3) *rr = *ss++;
  /* #65: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #66: @16 = ones(6x1,1nz) */
  w16 = 1.;
  /* #67: {NULL, @15, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w15 = w16;
  /* #68: @4 = (@4*@15) */
  w4 *= w15;
  /* #69: @18 = (@18*@4) */
  w18 *= w4;
  /* #70: @4 = (2.*@18) */
  w4 = (2.* w18 );
  /* #71: @12 = (@12*@4) */
  w12 *= w4;
  /* #72: @3 = (@3*@18) */
  w3 *= w18;
  /* #73: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #74: @8 = (@8*@3) */
  w8 *= w3;
  /* #75: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #76: @12 = (@12-@8) */
  w12 -= w8;
  /* #77: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #78: @8 = (@17*@12) */
  w8  = (w17*w12);
  /* #79: @8 = (-@8) */
  w8 = (- w8 );
  /* #80: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #81: @13 = (@13*@15) */
  w13 *= w15;
  /* #82: @12 = (@19*@12) */
  w12  = (w19*w12);
  /* #83: @13 = (@13+@12) */
  w13 += w12;
  /* #84: @13 = (-@13) */
  w13 = (- w13 );
  /* #85: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #86: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #87: @20 = (@20*@3) */
  w20 *= w3;
  /* #88: @24 = vertcat(@8, @13, @20, @21, @22, @23) */
  rr=w24;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w20;
  /* #89: @11 = @24[:3] */
  for (rr=w11, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #90: (@0[1:10:3] = @11) */
  for (rr=w0+1, ss=w11; rr!=w0+10; rr+=3) *rr = *ss++;
  /* #91: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #92: @13 = ones(6x1,1nz) */
  w13 = 1.;
  /* #93: {NULL, NULL, @20, NULL, NULL, NULL} = vertsplit(@13) */
  w20 = w13;
  /* #94: @8 = (@8*@20) */
  w8 *= w20;
  /* #95: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #96: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #97: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #98: @5 = (@5*@8) */
  w5 *= w8;
  /* #99: @1 = (@1*@5) */
  w1 *= w5;
  /* #100: @17 = (@17*@1) */
  w17 *= w1;
  /* #101: @19 = (@19*@1) */
  w19 *= w1;
  /* #102: @6 = (@6*@10) */
  w6 *= w10;
  /* #103: @7 = (@7*@6) */
  w7 *= w6;
  /* #104: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #105: @9 = (@9*@20) */
  w9 *= w20;
  /* #106: @7 = (@7*@9) */
  w7 *= w9;
  /* #107: @11 = vertcat(@17, @19, @7, @21, @22, @23) */
  rr=w11;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w7;
  /* #108: @24 = @11[:3] */
  for (rr=w24, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #109: (@0[2:11:3] = @24) */
  for (rr=w0+2, ss=w24; rr!=w0+11; rr+=3) *rr = *ss++;
  /* #110: @25 = @0' */
  casadi_trans(w0,casadi_s0, w25, casadi_s0, iw);
  /* #111: output[0][0] = @25 */
  casadi_copy(w25, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real avant_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 46;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
