/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) avant_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 4, 8, 11};
static const casadi_int casadi_s1[4] = {1, 5, 9, 12};
static const casadi_int casadi_s2[24] = {8, 8, 0, 0, 0, 4, 8, 11, 11, 13, 13, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 2, 3};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* avant_cost_y_hess:(i0[6],i1[2],i2[],i3[8],i4[],i5[5])->(o0[8x8,13nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+28, w19, w20, w21, w22, w23, w24, *w25=w+42, w26, w27, w28, w29, w30, w31, w32, w33, w35, *w37=w+56, *w38=w+60, *w40=w+64, *w41=w+67, *w43=w+70, *w44=w+72, *w45=w+74;
  /* #0: @0 = zeros(8x8,13nz) */
  casadi_clear(w0, 13);
  /* #1: @1 = 00 */
  /* #2: @2 = 00 */
  /* #3: @3 = 0.571429 */
  w3 = 5.7142857142857140e-01;
  /* #4: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #5: @5 = input[5][0] */
  w5 = arg[5] ? arg[5][0] : 0;
  /* #6: @6 = (@4-@5) */
  w6  = (w4-w5);
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @8 = input[0][1] */
  w8 = arg[0] ? arg[0][1] : 0;
  /* #9: @9 = input[5][1] */
  w9 = arg[5] ? arg[5][1] : 0;
  /* #10: @10 = (@8-@9) */
  w10  = (w8-w9);
  /* #11: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #12: @7 = (@7+@11) */
  w7 += w11;
  /* #13: @11 = 1.75 */
  w11 = 1.7500000000000000e+00;
  /* #14: @7 = (@7/@11) */
  w7 /= w11;
  /* #15: @11 = (2.*@7) */
  w11 = (2.* w7 );
  /* #16: @12 = sq(@7) */
  w12 = casadi_sq( w7 );
  /* #17: @12 = (-@12) */
  w12 = (- w12 );
  /* #18: @12 = exp(@12) */
  w12 = exp( w12 );
  /* #19: @13 = 180 */
  w13 = 180.;
  /* #20: @14 = 0.31831 */
  w14 = 3.1830988618379069e-01;
  /* #21: @15 = input[0][4] */
  w15 = arg[0] ? arg[0][4] : 0;
  /* #22: @16 = 0.2 */
  w16 = 2.0000000000000001e-01;
  /* #23: @17 = input[5][4] */
  w17 = arg[5] ? arg[5][4] : 0;
  /* #24: @18 = input[3][0] */
  casadi_copy(arg[3], 8, w18);
  /* #25: @18 = (@17*@18) */
  for (i=0, rr=w18, cs=w18; i<8; ++i) (*rr++)  = (w17*(*cs++));
  /* #26: {NULL, NULL, @17, @19, NULL, NULL, NULL, @20} = vertsplit(@18) */
  w17 = w18[2];
  w19 = w18[3];
  w20 = w18[7];
  /* #27: @16 = (@16*@20) */
  w16 *= w20;
  /* #28: @15 = (@15*@16) */
  w15 *= w16;
  /* #29: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #30: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #31: @20 = 90 */
  w20 = 90.;
  /* #32: @21 = 1 */
  w21 = 1.;
  /* #33: @22 = input[5][2] */
  w22 = arg[5] ? arg[5][2] : 0;
  /* #34: @23 = input[0][2] */
  w23 = arg[0] ? arg[0][2] : 0;
  /* #35: @23 = (@22-@23) */
  w23  = (w22-w23);
  /* #36: @24 = cos(@23) */
  w24 = cos( w23 );
  /* #37: @21 = (@21-@24) */
  w21 -= w24;
  /* #38: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #39: @21 = (@21*@17) */
  w21 *= w17;
  /* #40: @15 = (@15+@21) */
  w15 += w21;
  /* #41: @21 = (@12*@15) */
  w21  = (w12*w15);
  /* #42: @24 = (@11*@21) */
  w24  = (w11*w21);
  /* #43: @24 = (@3*@24) */
  w24  = (w3*w24);
  /* #44: @25 = ones(8x1,5nz) */
  casadi_fill(w25, 5, 1.);
  /* #45: {NULL, NULL, @26, NULL, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w26 = w25[2];
  /* #46: @27 = (2.*@26) */
  w27 = (2.* w26 );
  /* #47: @27 = (@24*@27) */
  w27  = (w24*w27);
  /* #48: @28 = (2.*@6) */
  w28 = (2.* w6 );
  /* #49: @29 = 0.571429 */
  w29 = 5.7142857142857140e-01;
  /* #50: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #51: @6 = (@6*@26) */
  w6 *= w26;
  /* #52: @6 = (@29*@6) */
  w6  = (w29*w6);
  /* #53: @30 = (2.*@6) */
  w30 = (2.* w6 );
  /* #54: @30 = (@21*@30) */
  w30  = (w21*w30);
  /* #55: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #56: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #57: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #58: @31 = (@15*@6) */
  w31  = (w15*w6);
  /* #59: @31 = (@11*@31) */
  w31  = (w11*w31);
  /* #60: @30 = (@30-@31) */
  w30 -= w31;
  /* #61: @30 = (@3*@30) */
  w30  = (w3*w30);
  /* #62: @31 = (@28*@30) */
  w31  = (w28*w30);
  /* #63: @27 = (@27+@31) */
  w27 += w31;
  /* #64: @27 = (-@27) */
  w27 = (- w27 );
  /* #65: @31 = cos(@22) */
  w31 = cos( w22 );
  /* #66: @32 = 0.1 */
  w32 = 1.0000000000000001e-01;
  /* #67: @33 = 25 */
  w33 = 25.;
  /* #68: @33 = (@33*@19) */
  w33 *= w19;
  /* #69: @4 = (@4-@5) */
  w4 -= w5;
  /* #70: @4 = (@4*@31) */
  w4 *= w31;
  /* #71: @8 = (@8-@9) */
  w8 -= w9;
  /* #72: @22 = sin(@22) */
  w22 = sin( w22 );
  /* #73: @8 = (@8*@22) */
  w8 *= w22;
  /* #74: @4 = (@4+@8) */
  w4 += w8;
  /* #75: @8 = 25 */
  w8 = 25.;
  /* #76: @4 = (@4-@8) */
  w4 -= w8;
  /* #77: @8 = 10 */
  w8 = 10.;
  /* #78: @4 = (@4/@8) */
  w4 /= w8;
  /* #79: @4 = tanh(@4) */
  w4 = tanh( w4 );
  /* #80: @8 = (2.*@4) */
  w8 = (2.* w4 );
  /* #81: @9 = 1 */
  w9 = 1.;
  /* #82: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #83: @9 = (@9-@4) */
  w9 -= w4;
  /* #84: @4 = 0.1 */
  w4 = 1.0000000000000001e-01;
  /* #85: @26 = (@31*@26) */
  w26  = (w31*w26);
  /* #86: @26 = (@4*@26) */
  w26  = (w4*w26);
  /* #87: @26 = (@9*@26) */
  w26  = (w9*w26);
  /* #88: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #89: @26 = (@33*@26) */
  w26  = (w33*w26);
  /* #90: @26 = (@32*@26) */
  w26  = (w32*w26);
  /* #91: @5 = (@31*@26) */
  w5  = (w31*w26);
  /* #92: @27 = (@27-@5) */
  w27 -= w5;
  /* #93: @5 = (2.*@10) */
  w5 = (2.* w10 );
  /* #94: @30 = (@5*@30) */
  w30  = (w5*w30);
  /* #95: @30 = (-@30) */
  w30 = (- w30 );
  /* #96: @26 = (@22*@26) */
  w26  = (w22*w26);
  /* #97: @30 = (@30-@26) */
  w30 -= w26;
  /* #98: @26 = sin(@23) */
  w26 = sin( w23 );
  /* #99: @19 = (@17*@6) */
  w19  = (w17*w6);
  /* #100: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #101: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #102: @34 = 00 */
  /* #103: @35 = 0.31831 */
  w35 = 3.1830988618379069e-01;
  /* #104: @6 = (@13*@6) */
  w6  = (w13*w6);
  /* #105: @6 = (@35*@6) */
  w6  = (w35*w6);
  /* #106: @6 = (@16*@6) */
  w6  = (w16*w6);
  /* #107: @6 = (-@6) */
  w6 = (- w6 );
  /* #108: @36 = 00 */
  /* #109: @37 = vertcat(@1, @2, @27, @30, @19, @34, @6, @36) */
  rr=w37;
  *rr++ = w27;
  *rr++ = w30;
  *rr++ = w19;
  *rr++ = w6;
  /* #110: @38 = @37[:4] */
  for (rr=w38, ss=w37+0; ss!=w37+4; ss+=1) *rr++ = *ss;
  /* #111: (@0[0, 4, 8, 11] = @38) */
  for (cii=casadi_s0, rr=w0, ss=w38; cii!=casadi_s0+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #112: @1 = 00 */
  /* #113: @2 = 00 */
  /* #114: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #115: @27 = ones(8x1,1nz) */
  w27 = 1.;
  /* #116: {NULL, NULL, NULL, @30, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w30 = w27;
  /* #117: @10 = (@10*@30) */
  w10 *= w30;
  /* #118: @29 = (@29*@10) */
  w29 *= w10;
  /* #119: @10 = (2.*@29) */
  w10 = (2.* w29 );
  /* #120: @21 = (@21*@10) */
  w21 *= w10;
  /* #121: @7 = (@7*@29) */
  w7 *= w29;
  /* #122: @7 = (@12*@7) */
  w7  = (w12*w7);
  /* #123: @15 = (@15*@7) */
  w15 *= w7;
  /* #124: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #125: @21 = (@21-@15) */
  w21 -= w15;
  /* #126: @21 = (@3*@21) */
  w21  = (w3*w21);
  /* #127: @15 = (@28*@21) */
  w15  = (w28*w21);
  /* #128: @15 = (-@15) */
  w15 = (- w15 );
  /* #129: @29 = (@22*@30) */
  w29  = (w22*w30);
  /* #130: @4 = (@4*@29) */
  w4 *= w29;
  /* #131: @9 = (@9*@4) */
  w9 *= w4;
  /* #132: @8 = (@8*@9) */
  w8 *= w9;
  /* #133: @33 = (@33*@8) */
  w33 *= w8;
  /* #134: @32 = (@32*@33) */
  w32 *= w33;
  /* #135: @31 = (@31*@32) */
  w31 *= w32;
  /* #136: @15 = (@15-@31) */
  w15 -= w31;
  /* #137: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #138: @24 = (@24*@30) */
  w24 *= w30;
  /* #139: @21 = (@5*@21) */
  w21  = (w5*w21);
  /* #140: @24 = (@24+@21) */
  w24 += w21;
  /* #141: @24 = (-@24) */
  w24 = (- w24 );
  /* #142: @22 = (@22*@32) */
  w22 *= w32;
  /* #143: @24 = (@24-@22) */
  w24 -= w22;
  /* #144: @22 = (@17*@7) */
  w22  = (w17*w7);
  /* #145: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #146: @26 = (@26*@22) */
  w26 *= w22;
  /* #147: @7 = (@13*@7) */
  w7  = (w13*w7);
  /* #148: @35 = (@35*@7) */
  w35 *= w7;
  /* #149: @35 = (@16*@35) */
  w35  = (w16*w35);
  /* #150: @35 = (-@35) */
  w35 = (- w35 );
  /* #151: @36 = 00 */
  /* #152: @38 = vertcat(@1, @2, @15, @24, @26, @34, @35, @36) */
  rr=w38;
  *rr++ = w15;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w35;
  /* #153: @37 = @38[:4] */
  for (rr=w37, ss=w38+0; ss!=w38+4; ss+=1) *rr++ = *ss;
  /* #154: (@0[1, 5, 9, 12] = @37) */
  for (cii=casadi_s1, rr=w0, ss=w37; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #155: @1 = 00 */
  /* #156: @2 = 00 */
  /* #157: @15 = sin(@23) */
  w15 = sin( w23 );
  /* #158: @24 = ones(8x1,1nz) */
  w24 = 1.;
  /* #159: {NULL, NULL, NULL, NULL, @26, NULL, NULL, NULL} = vertsplit(@24) */
  w26 = w24;
  /* #160: @15 = (@15*@26) */
  w15 *= w26;
  /* #161: @15 = (@20*@15) */
  w15  = (w20*w15);
  /* #162: @15 = (@17*@15) */
  w15  = (w17*w15);
  /* #163: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #164: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #165: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #166: @24 = (@28*@15) */
  w24  = (w28*w15);
  /* #167: @15 = (@5*@15) */
  w15  = (w5*w15);
  /* #168: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #169: @20 = (@20*@17) */
  w20 *= w17;
  /* #170: @23 = cos(@23) */
  w23 = cos( w23 );
  /* #171: @23 = (@23*@26) */
  w23 *= w26;
  /* #172: @20 = (@20*@23) */
  w20 *= w23;
  /* #173: @36 = 00 */
  /* #174: @39 = 00 */
  /* #175: @40 = vertcat(@1, @2, @24, @15, @20, @34, @36, @39) */
  rr=w40;
  *rr++ = w24;
  *rr++ = w15;
  *rr++ = w20;
  /* #176: @41 = @40[:3] */
  for (rr=w41, ss=w40+0; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #177: (@0[2:14:4] = @41) */
  for (rr=w0+2, ss=w41; rr!=w0+14; rr+=4) *rr = *ss++;
  /* #178: @1 = 00 */
  /* #179: @2 = 00 */
  /* #180: @24 = ones(8x1,1nz) */
  w24 = 1.;
  /* #181: {NULL, NULL, NULL, NULL, NULL, NULL, @15, NULL} = vertsplit(@24) */
  w15 = w24;
  /* #182: @16 = (@16*@15) */
  w16 *= w15;
  /* #183: @14 = (@14*@16) */
  w14 *= w16;
  /* #184: @13 = (@13*@14) */
  w13 *= w14;
  /* #185: @12 = (@12*@13) */
  w12 *= w13;
  /* #186: @11 = (@11*@12) */
  w11 *= w12;
  /* #187: @3 = (@3*@11) */
  w3 *= w11;
  /* #188: @28 = (@28*@3) */
  w28 *= w3;
  /* #189: @28 = (-@28) */
  w28 = (- w28 );
  /* #190: @5 = (@5*@3) */
  w5 *= w3;
  /* #191: @5 = (-@5) */
  w5 = (- w5 );
  /* #192: @36 = 00 */
  /* #193: @39 = 00 */
  /* #194: @42 = 00 */
  /* #195: @43 = vertcat(@1, @2, @28, @5, @36, @34, @39, @42) */
  rr=w43;
  *rr++ = w28;
  *rr++ = w5;
  /* #196: @44 = @43[:2] */
  for (rr=w44, ss=w43+0; ss!=w43+2; ss+=1) *rr++ = *ss;
  /* #197: (@0[3:11:4] = @44) */
  for (rr=w0+3, ss=w44; rr!=w0+11; rr+=4) *rr = *ss++;
  /* #198: @45 = @0' */
  casadi_trans(w0,casadi_s2, w45, casadi_s2, iw);
  /* #199: output[0][0] = @45 */
  casadi_copy(w45, 13, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int avant_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int avant_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int avant_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void avant_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void avant_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int avant_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real avant_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* avant_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s5;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* avant_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int avant_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 87;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
